import { Image } from 'expo-image';
import { Link, type Href } from 'expo-router';
import Head from 'expo-router/head';
import { useState } from 'react';
import { useApp } from '@/hooks/use-app';
import { contact, services, servicePath } from './content';
import { WebBrand } from './brand.web';
const artwork: Record<string, number> = {
  company: require('../../../assets/images/action-icons/company.png'), llp: require('../../../assets/images/action-icons/llp.png'),
  'gst-registration': require('../../../assets/images/action-icons/gst-registration.png'), food: require('../../../assets/images/action-icons/food.png'),
  retail: require('../../../assets/images/action-icons/retail.png'), 'gst-return': require('../../../assets/images/action-icons/gst-return.png'),
  'new-business': require('../../../assets/images/action-icons/new-business.png'), online: require('../../../assets/images/action-icons/online.png'),
  manufacturing: require('../../../assets/images/action-icons/manufacturing.png'), branch: require('../../../assets/images/action-icons/branch.png'),
  'business-check': require('../../../assets/images/action-icons/business-check.png'),
};
const faqs = [
  ['Can I use my existing RegisterBox account?', 'Yes. Sign in with the same email used in the app. The website uses the same account, business profiles, documents and backend services.'],
  ['What happens when I start an application?', 'You sign in, choose a business, answer relevant questions and upload supporting documents. Your progress is saved as a draft. Professional review and government submission are separate steps; a saved draft is not a filed application.'],
  ['Can I manage more than one business?', 'Yes. Switch between saved business profiles in your workspace. Applications, documents and GST workspaces remain linked to the selected business.'],
  ['Can I pay or file GST returns here?', 'You can prepare application and GST drafts and use the connected services available in your account. Live payment collection is not configured yet. GST portal writes and filing depend on provider availability, consent and the backend release controls.'],
  ['Are fees and government approvals guaranteed?', 'No. Requirements, government fees and processing depend on the service and authority. Confirm the scope and quote with RegisterBox before proceeding. Government decisions cannot be guaranteed.'],
  ['How do I get help?', 'WhatsApp +91 81477 77843 or email registerbox@yahoo.com. You can also prepare a detailed enquiry on our contact page.'],
];
export default function LandingPage() {
  const { session } = useApp();
  const [menu, setMenu] = useState(false);
  const [filter, setFilter] = useState('Popular');
  const [search, setSearch] = useState('');
  const destination = (path: string): Href => session ? path as Href : { pathname: '/auth', params: { next: path } };
  const shown = services.filter((service, index) => (filter==='All services'||filter==='Popular'&&index<6||service.group===filter) && `${service.title} ${service.detail}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="rb-website">
    <Head><title>RegisterBox | Your business. Sorted.</title><meta name="description" content="Start, register and manage your business with RegisterBox. Guided application drafts, business documents, compliance tracking and GST workspaces, connected to your existing account."/><link rel="canonical" href="https://registerbox.in/"/><meta property="og:title" content="RegisterBox — Your business. Sorted."/><meta property="og:description" content="Less paperwork. More possibility. One workspace for your business journey."/></Head>
    <a className="rb-skip" href="#main-content">Skip to content</a>
    <div className="rb-announcement"><span className="rb-online-dot"/>Built for the way India does business.<a href="#how-it-works">Meet your business workspace <span>↗</span></a></div>
    <header className="rb-header rb-container"><WebBrand/><nav className={menu?'rb-top-nav is-open':'rb-top-nav'} aria-label="Main navigation"><a href="#services" onClick={()=>setMenu(false)}>Services</a><a href="#workspace" onClick={()=>setMenu(false)}>Your workspace</a><a href="#how-it-works" onClick={()=>setMenu(false)}>How it works</a><Link href="/contact" onPress={()=>setMenu(false)}>Contact</Link></nav><div className="rb-header-actions"><Link href={session?'/dashboard':'/auth'} className="rb-login">{session?'My workspace':'Log in'}</Link><Link href={destination('/dashboard')} className="rb-button rb-button-small">Get started <span>↗</span></Link><button className="rb-menu-button" aria-label="Toggle main menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?'Close':'Menu'} {menu?'−':'+'}</button></div></header>
    <main id="main-content">
      <section className="rb-hero rb-container">
        <div className="rb-hero-copy"><div className="rb-eyebrow"><span/>BIG AMBITIONS. LESS PAPERWORK.</div><h1>You build the business.<br/><span>We help sort</span><br/>the rest<span className="rb-period">.</span></h1><p>From your first registration to your next chapter. Bring applications, documents and compliance together in one simple business workspace.</p><div className="rb-hero-actions"><Link href={destination(servicePath('new'))} className="rb-button">Start my business <span>↗</span></Link><a href="#services" className="rb-secondary-button">Explore services <span>↓</span></a></div><div className="rb-hero-notes"><span>✓ Guided, step by step</span><span>✓ One account, app & web</span></div></div>
        <div className="rb-hero-visual"><div className="rb-orbit rb-orbit-one"/><div className="rb-orbit rb-orbit-two"/><span className="rb-spark rb-spark-one">✦</span><span className="rb-spark rb-spark-two">✧</span><div className="rb-preview"><div className="rb-preview-top"><div className="rb-preview-mark">R<span>★</span></div><span>YOUR BUSINESS, AT A GLANCE</span><span className="rb-preview-dots">•••</span></div><div className="rb-preview-body"><div className="rb-preview-greeting"><div><small>LET’S MAKE IT HAPPEN</small><h3>A little clarity.<br/>A lot of possibility.</h3></div><div className="rb-mini-star">✦</div></div><div className="rb-preview-stats"><div><span>01</span><small>Business profile</small></div><div><span>02</span><small>Application drafts</small></div><div><span>03</span><small>Saved documents</small></div></div><div className="rb-preview-row"><div className="rb-preview-icon">▤</div><div><b>Business registration</b><small>Details saved · ready for review</small></div><span className="rb-status">Draft</span></div><div className="rb-preview-row"><div className="rb-preview-icon">▱</div><div><b>Your document wallet</b><small>Everything in its place</small></div><span>↗</span></div><div className="rb-preview-bottom"><span>✦</span><p>Not sure what comes next?<br/><b>Your AI assistant can help.</b></p><span>→</span></div><small className="rb-demo-label">Illustrative workspace · sample data</small></div></div><div className="rb-floating-note"><span>✓</span><div><b>One place. Every next step.</b><small>Pick up where you left off.</small></div></div></div>
      </section>
      <div className="rb-capabilities rb-container"><span>FROM DAY ONE<br/><b>TO WHAT’S NEXT.</b></span><p><span>▦</span> Business registrations</p><p><span>₹</span> GST workspace</p><p><span>▱</span> Document wallet</p><p><span>✦</span> AI guidance</p></div>
      <section className="rb-services-section" id="services"><div className="rb-container"><div className="rb-section-heading"><div><div className="rb-eyebrow">A GOOD PLACE TO START</div><h2>What’s your next move?</h2></div><p>A new idea, a growing business, or paperwork to catch up on. Let’s find your starting point.</p></div><div className="rb-services-controls"><div className="rb-filters" aria-label="Filter services">{['Popular','Start a business','Registrations','Manage & comply','All services'].map(item=><button key={item} className={filter===item?'is-active':''} aria-pressed={filter===item} onClick={()=>setFilter(item)}>{item}</button>)}</div><label className="rb-search"><span aria-hidden="true">⌕</span><input type="search" aria-label="Search services" placeholder="Find a service" value={search} onChange={event=>{setSearch(event.target.value);if(event.target.value)setFilter('All services');}}/></label></div><div className="rb-services-grid">{shown.map(service=><Link href={destination(servicePath(service.category))} key={service.category} className="rb-service-card"><div className="rb-service-card-top"><Image source={artwork[service.icon]} contentFit="contain" style={{width:68,height:68}} alt=""/><span className="rb-card-arrow">↗</span></div><small>{service.tag}</small><h3>{service.title}</h3><p>{service.detail}</p><div className="rb-service-footer">{service.category==='gst'?'Open workspace':'Start application'} <span>→</span></div></Link>)}</div>{!shown.length&&<div className="rb-empty" role="status">No services match “{search}”. <button onClick={()=>{setSearch('');setFilter('All services');}}>View all services</button></div>}<div className="rb-services-help"><span>Not sure which route is right for you?</span><Link href={destination('/ai')}>Ask RegisterBox AI <span>↗</span></Link><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer">Talk to our team ↗</a></div></div></section>
      <section className="rb-workspace-section rb-container" id="workspace"><div className="rb-workspace-illustration"><div className="rb-folder-stack"><div className="rb-folder-back"/><div className="rb-folder"><div className="rb-folder-tab"/><span>YOUR BUSINESS</span><h3>Everything<br/>in good order.</h3><div className="rb-folder-doc"><span>▤</span><div><b>Registration documents</b><small>Saved to your business profile</small></div><span>✓</span></div><div className="rb-folder-doc"><span>▤</span><div><b>Application progress</b><small>Your next steps, made visible</small></div><span>✓</span></div><div className="rb-folder-doc"><span>₹</span><div><b>GST workspace</b><small>Prepare. Review. Track.</small></div><span>✓</span></div></div></div><span className="rb-illustration-caption">LESS SEARCHING. MORE DOING.</span></div><div className="rb-workspace-copy"><div className="rb-eyebrow">ONE WORKSPACE. FEWER LOOSE ENDS.</div><h2>Your business has<br/>a home here.</h2><p>Paperwork shouldn’t be scattered across chats, folders and devices. Keep the important things connected to the right business.</p><ul><li><span>01</span><div><b>A document wallet that stays with you</b><p>Upload evidence once and access your saved documents and delivered certificates.</p></div></li><li><span>02</span><div><b>A clear view of your applications</b><p>See actual application status and distinguish preparation from submission.</p></div></li><li><span>03</span><div><b>Connected tools, when you need them</b><p>Explore GST drafts, purchases, DigiLocker and Tally through the same account.</p></div></li></ul><Link href={destination('/dashboard')} className="rb-text-link">Open my workspace <span>↗</span></Link></div></section>
      <section className="rb-process" id="how-it-works"><div className="rb-container"><div className="rb-eyebrow">SMALL STEPS. REAL PROGRESS.</div><h2>From “where do I start?”<br/>to “I’ve got this.”</h2><div className="rb-process-grid">{[['01','Tell us your goal','Choose your service and sign in securely with an email code.'],['02','Make it your business','Answer relevant questions, choose a business profile and gather your documents.'],['03','Save, review, move forward','Keep a draft, review what’s missing and track the next steps in your workspace.']].map(([number,title,body])=><div key={number}><span className="rb-step-number">{number}</span><h3>{title}</h3><p>{body}</p></div>)}</div><p className="rb-process-note">Government submission and professional review are separate from saving an application draft.</p></div></section>
      <section className="rb-ai-section rb-container"><div className="rb-ai-icon">✦</div><div><div className="rb-eyebrow">MEET REGISTERBOX AI</div><h2>A little guidance goes a long way.</h2><p>Describe your idea in plain language. Get help understanding your options and finding a starting point.</p><small>AI guidance supports your decisions. Service eligibility and filing details still need review.</small></div><Link href={destination('/ai')} className="rb-button">Let’s talk business <span>↗</span></Link></section>
      <section className="rb-faq-section rb-container"><div><div className="rb-eyebrow">GOOD QUESTIONS. CLEAR ANSWERS.</div><h2>A few things<br/>you might ask.</h2><p>Still have a question?<br/>We’re a message away.</p><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer" className="rb-text-link">Chat on WhatsApp ↗</a></div><div className="rb-faq-list">{faqs.map(([question,answer])=><details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="rb-bottom-cta rb-container"><div className="rb-eyebrow">YOUR NEXT CHAPTER STARTS HERE</div><h2>Big plans?<br/>Let’s make room for them<span>✦</span></h2><div><Link href={destination(servicePath('new'))} className="rb-button rb-button-white">Get started with RegisterBox ↗</Link><Link href="/contact" className="rb-cta-contact">Talk to our team ↗</Link></div><span className="rb-cta-orbit"/></section>
    </main>
    <footer className="rb-footer rb-container"><div className="rb-footer-grid"><div><WebBrand/><p>Less paperwork. More possibility.<br/>Your business journey, brought together.</p><a href={`mailto:${contact.email}`}>{contact.email} ↗</a></div><div><h4>Start & grow</h4>{services.slice(0,5).map(service=><Link key={service.category} href={destination(servicePath(service.category))}>{service.title}</Link>)}</div><div><h4>Your workspace</h4>{[['/dashboard','Business overview'],['/documents','Document wallet'],['/compliance','Application tracking'],['/gst','GST workspace'],['/tally','Connect Tally']].map(([path,label])=><Link key={path} href={destination(path)}>{label}</Link>)}</div><div><h4>Come say hello</h4><address>{contact.address}</address><a href={contact.whatsapp} target="_blank" rel="noopener noreferrer">WhatsApp {contact.phone} ↗</a><Link href="/contact">Contact RegisterBox ↗</Link></div></div><div className="rb-footer-bottom"><span>© {new Date().getFullYear()} RegisterBox. All rights reserved.</span><div><Link href={{pathname:'/policies',params:{section:'privacy'}}}>Privacy & data</Link><Link href={{pathname:'/policies',params:{section:'service'}}}>Service information</Link></div><span>Built for business in India 🇮🇳</span></div></footer>
  </div>;
}
