import { useState } from 'react';
import { Pressable, Text, View } from 'react-native';
import { Button, ErrorBanner, Field } from '@/components/registerbox-ui';
import { palette } from '@/constants/design';
import { appendInvoice, emptyInvoice, invoiceAmounts } from '@/lib/gst-invoice';
import { blank3b } from '../../supabase/functions/_shared/gstr3b';
import { Gstr3bEditor } from './gstr3b-editor';
import { Gstr1SectionEditor } from './gstr1-section-editor';

type Obj=Record<string,unknown>;
const note={color:palette.muted,lineHeight:21};
const checks:Record<string,string>={noSales:'No outward supplies (including nil-rated, exempt or non-GST sales).',noAdjustments:'No credit/debit notes, amendments, advances or other reportable adjustments.',completeBooks:'I checked the complete books for this period.',noPurchases:'No inward supplies or purchases of goods/services.',noItc:'No ITC to claim, reverse or adjust.',noLiability:'No tax, reverse-charge, interest or late-fee liability outstanding.',noAutoPopulation:'No GSTR-1/IFF or GSTR-2B auto-populated data and no manual return entries.',gstr1FiledNil:'GSTR-1 for this period has been filed as nil and I checked prior filing prerequisites.'};
const names:Record<string,string>={sup_details:'3.1 · Supplies',osup_det:'Taxable outward supplies',osup_zero:'Zero-rated outward supplies',osup_nil_exmp:'Nil-rated / exempt outward supplies',isup_rev:'Inward supplies under reverse charge',osup_nongst:'Non-GST outward supplies',txval:'Taxable value ₹',iamt:'IGST ₹',camt:'CGST ₹',samt:'SGST / UTGST ₹',csamt:'Cess ₹',itc_elg:'4 · Input tax credit',itc_net:'Net eligible ITC',itc_avl:'ITC available',itc_rev:'ITC reversals',itc_inelg:'Other ITC details',inward_sup:'5 · Exempt / nil / non-GST inward supplies',inter_sup:'3.2 · Interstate supplies',intr_ltfee:'5.1 · Interest and late fee',intr_details:'Interest',ltfee_details:'Late fee',pdcash:'Pay from cash ledger',pditc:'Use eligible ITC',ipd:'IGST tax paid',cpd:'CGST tax paid',spd:'SGST tax paid',cspd:'Cess paid'};
export function AmountTree({value,onChange,disabled,path=''}:{value:unknown;onChange:(v:unknown)=>void;disabled:boolean;path?:string}) {
  if(Array.isArray(value)) return <View style={{gap:12}}>{value.map((item,index)=><View key={index} style={{gap:8}}><Text style={note}>{String((item as Obj)?.ty||`Row ${index+1}`)}</Text><AmountTree value={item} disabled={disabled} path={path} onChange={next=>onChange(value.map((old,i)=>i===index?next:old))}/></View>)}</View>;
  if(value && typeof value==='object') return <View style={{gap:10}}>{Object.entries(value as Obj).map(([key,item])=>{
    if(['gstin','fp','ret_period','ty'].includes(key))return null;
    return <View key={key} style={{gap:6}}>{typeof item==='object'?<Text style={{color:palette.ink,fontWeight:'700'}}>{names[key]||key.replaceAll('_',' ')}</Text>:null}<AmountTree value={item} path={key} disabled={disabled} onChange={next=>onChange({...value,[key]:next})}/></View>;
  })}</View>;
  return <Field label={names[path]||path.replaceAll('_',' ')} keyboardType={typeof value==='number'?'decimal-pad':'default'} value={String(value??'')} editable={!disabled} onChangeText={text=>onChange(typeof value==='number' && /^-?\d+(\.\d+)?$/.test(text)?Number(text):text)}/>;
}
export function GstGuidedEditor({payload,gstin,period,form,onChange,disabled}:{payload:string;gstin:string;period:string;form:'gstr-1'|'gstr-3b';onChange:(text:string)=>void;disabled:boolean}) {
  const [invoice,setInvoice]=useState({...emptyInvoice}),[error,setError]=useState('');
  let data:Obj={};try{const parsed=JSON.parse(payload||'{}');if(parsed&&typeof parsed==='object'&&!Array.isArray(parsed))data=parsed;}catch{/* Advanced malformed data stays visible in advanced editor. */}
  const nil=data.registerbox_nil===true;
  const update=(value:Obj)=>onChange(JSON.stringify(value,null,2));
  const declarations=(data.declarations||{}) as Obj;
  let preview='Enter amounts to preview the tax split.';
  try{const a=invoiceAmounts(invoice,gstin);preview=`IGST ₹${a.igst.toFixed(2)} · CGST ₹${a.cgst.toFixed(2)} · SGST ₹${a.sgst.toFixed(2)} · Cess ₹${a.cess.toFixed(2)}\nInvoice total ₹${a.total.toFixed(2)}`;}catch{/* Incomplete input is not a zero total. */}
  return <View style={{gap:14}}>
    {!payload?<><Text style={note}>Choose what you need for this period. No code or JSON is required for invoice entry or nil declarations.</Text><Button title="File a nil return" disabled={disabled||!gstin||!/^\d{6}$/.test(period)} onPress={()=>update({gstin,ret_period:period,registerbox_nil:true,declarations:{}})}/><Button title="Prepare a regular return" variant="secondary" disabled={disabled||!gstin} onPress={()=>update(form==='gstr-1'?{gstin,fp:period,b2b:[]}:blank3b(gstin,period))}/></>:null}
    {nil?<><View style={{alignItems:'center',paddingVertical:18,gap:12}}><View style={{width:74,height:74,borderRadius:37,backgroundColor:'#EDF4FF',alignItems:'center',justifyContent:'center'}}><Text style={{fontSize:35,color:palette.blue}}>▤</Text></View><Text style={{color:palette.ink,fontWeight:'800',fontSize:18}}>File Nil {form.toUpperCase()}</Text><Text style={{fontSize:12,color:palette.muted}}>Confirm your activity for this return period</Text></View>{Object.entries(checks).filter(([key])=>form==='gstr-3b'||['noSales','noAdjustments','completeBooks'].includes(key)).map(([key,label])=><Pressable key={key} accessibilityRole="checkbox" accessibilityState={{checked:declarations[key]===true,disabled}} disabled={disabled} onPress={()=>update({...data,declarations:{...declarations,[key]:declarations[key]!==true}})} style={{flexDirection:'row',gap:10,alignItems:'flex-start',paddingVertical:6}}><View style={{width:20,height:20,borderRadius:10,borderWidth:1.5,borderColor:declarations[key]===true?palette.green:palette.line,backgroundColor:declarations[key]===true?palette.green:palette.white,alignItems:'center',justifyContent:'center'}}><Text style={{color:palette.white,fontSize:12}}>✓</Text></View><Text style={{flex:1,color:palette.ink,fontSize:12,lineHeight:18}}>{label}</Text></Pressable>)}<View style={{backgroundColor:'#EDF4FF',borderRadius:10,padding:12}}><Text style={{fontSize:11,lineHeight:17,color:palette.muted}}>A nil return reports no activity for the selected period. We’ll compare the saved GST records before you authorize filing.</Text></View></>:payload&&form==='gstr-1'?<>
      <Text style={note}>Registered-customer sales (B2B), regular domestic supply. Add one rate per invoice here; mixed-rate invoices and other sections need the advanced workflow. Select the actual rate and place of supply—customer location is not a substitute.</Text>
      {Object.entries({customer:'Customer GSTIN',number:'Invoice number',date:'Invoice date · DD-MM-YYYY',pos:'Place of supply · state code',taxable:'Taxable value ₹',rate:'Applicable GST rate %',cess:'Cess amount ₹'}).map(([key,label])=><Field key={key} label={label} value={invoice[key as keyof typeof invoice]} editable={!disabled} autoCapitalize={key==='customer'?'characters':'none'} keyboardType={['taxable','rate','cess'].includes(key)?'decimal-pad':'default'} onChangeText={value=>setInvoice({...invoice,[key]:key==='customer'?value.toUpperCase():value})}/>)}
      <Text selectable style={note}>{preview}</Text><ErrorBanner message={error}/><Button title="Add invoice to draft" disabled={disabled} onPress={()=>{try{update(appendInvoice(data,invoice,gstin,period));setInvoice({...emptyInvoice});setError('');}catch(cause){setError(cause instanceof Error?cause.message:'Check invoice fields.');}}}/>
      {Array.isArray(data.b2b)?data.b2b.flatMap((group: {ctin:string;inv:Obj[]})=>group.inv.map(inv=><View key={String(inv.inum)} style={{gap:6,padding:12,backgroundColor:'#F1F5FF',borderRadius:12}}><Text selectable>{String(inv.inum)} · {String(inv.idt)} · ₹{String(inv.val)}</Text><Text selectable style={note}>{group.ctin}</Text><Button title="Remove invoice" variant="ghost" disabled={disabled} onPress={()=>update({...data,b2b:(data.b2b as {ctin:string;inv:Obj[]}[]).map(g=>({...g,inv:g.inv.filter(i=>i.inum!==inv.inum)})).filter(g=>g.inv.length)})}/></View>)):null}
      <Gstr1SectionEditor data={data} gstin={gstin} period={period} disabled={disabled} onChange={update}/>
    </>:payload?<Gstr3bEditor data={data} onChange={update} disabled={disabled}/>:null}
    {payload?<Button title="Change return type / start over" variant="ghost" disabled={disabled} onPress={()=>{onChange('');setError('');}}/>:null}
  </View>;
}
