import { useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { palette } from '@/constants/design';

export function GstHeader({title,onBack}:{title:string;onBack:()=>void}) {
  return <View style={styles.header}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={onBack} style={styles.back}><Text style={{fontSize:28,color:palette.ink}}>‹</Text></Pressable><Text style={styles.headerTitle}>{title}</Text><View style={{width:36}}/></View>;
}
export function GstTabs({items,value,onChange}:{items:string[];value:string;onChange:(value:string)=>void}) {
  return <View style={styles.tabs}>{items.map(item=><Pressable key={item} accessibilityRole="tab" accessibilityState={{selected:item===value}} onPress={()=>onChange(item)} style={[styles.tab,item===value&&styles.activeTab]}><Text style={[styles.tabLabel,item===value&&{color:palette.blue}]}>{item}</Text></Pressable>)}</View>;
}
export function GstSelect({label,value,options,onChange,disabled=false}:{label:string;value:string;options:{label:string;value:string}[];onChange:(value:string)=>void;disabled?:boolean}) {
  const [open,setOpen]=useState(false);
  return <View style={{gap:6}}><Text style={styles.label}>{label}</Text><Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled} onPress={()=>setOpen(true)} style={styles.select}><Text style={{fontSize:13,color:palette.ink,fontWeight:'600'}}>{options.find(option=>option.value===value)?.label||'Select'}</Text><Text style={{color:palette.muted}}>⌄</Text></Pressable><Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={styles.overlay}><Pressable accessibilityLabel="Close options" onPress={()=>setOpen(false)} style={StyleSheet.absoluteFill}/><View style={styles.sheet}><Text style={styles.sheetTitle}>{label}</Text><ScrollView>{options.map(option=><Pressable accessibilityRole="radio" accessibilityState={{checked:option.value===value}} key={option.value} onPress={()=>{onChange(option.value);setOpen(false);}} style={styles.option}><Text style={{color:option.value===value?palette.blue:palette.ink,fontSize:14}}>{option.label}</Text><Text style={{color:palette.blue}}>{option.value===value?'●':'○'}</Text></Pressable>)}</ScrollView><Pressable onPress={()=>setOpen(false)} style={styles.option}><Text style={{color:palette.blue}}>Cancel</Text></Pressable></View></View></Modal></View>;
}
export function GstActionRow({icon,title,onPress}:{icon:string;title:string;onPress:()=>void}) {return <Pressable accessibilityRole="button" onPress={onPress} style={styles.action}><View style={styles.actionIcon}><Text style={{color:palette.blue,fontSize:16}}>{icon}</Text></View><Text style={styles.actionTitle}>{title}</Text><Text style={{color:palette.muted}}>›</Text></Pressable>;}
export const gstStyles=StyleSheet.create({card:{padding:15,borderRadius:13,backgroundColor:palette.white,borderWidth:1,borderColor:'#E7EDF7',gap:13},title:{fontSize:14,fontWeight:'800',color:palette.ink},caption:{fontSize:12,lineHeight:18,color:palette.muted},stack:{gap:16},});
const styles=StyleSheet.create({header:{height:46,flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:14},back:{width:36,height:42,justifyContent:'center'},headerTitle:{fontSize:15,fontWeight:'800',color:palette.ink,textAlign:'center',flex:1},tabs:{flexDirection:'row',padding:4,borderRadius:10,backgroundColor:'#EDF1F7',gap:3},tab:{flex:1,alignItems:'center',paddingVertical:10,borderRadius:7},activeTab:{backgroundColor:palette.white,boxShadow:'0 2px 5px rgba(20,60,130,0.07)',borderBottomWidth:2,borderBottomColor:palette.blue},tabLabel:{fontSize:11,color:palette.muted,fontWeight:'600'},label:{fontSize:11,color:palette.muted},select:{minHeight:44,borderWidth:1,borderColor:palette.line,borderRadius:8,paddingHorizontal:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:palette.white},overlay:{flex:1,backgroundColor:'rgba(9,23,58,0.3)',alignItems:'center',justifyContent:'center',padding:24},sheet:{width:'100%',maxWidth:380,maxHeight:'75%',backgroundColor:palette.white,borderRadius:18,padding:18},sheetTitle:{fontSize:16,fontWeight:'800',color:palette.ink,marginBottom:10},option:{minHeight:48,paddingVertical:12,flexDirection:'row',justifyContent:'space-between',alignItems:'center',borderBottomWidth:1,borderBottomColor:'#EDF1F7'},action:{minHeight:48,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:'#F1F4FA'},actionIcon:{height:29,width:29,borderRadius:8,backgroundColor:'#EDF4FF',alignItems:'center',justifyContent:'center'},actionTitle:{flex:1,fontSize:12,color:palette.muted},});
