-- Cover foreign keys used by ownership checks, joins, queues, and audit views.
create index if not exists ai_conversations_business_id_fkey_idx on public.ai_conversations (business_id);
create index if not exists ai_conversations_user_id_fkey_idx on public.ai_conversations (user_id);
create index if not exists ai_messages_conversation_id_fkey_idx on public.ai_messages (conversation_id);
create index if not exists application_events_application_id_fkey_idx on public.application_events (application_id);
create index if not exists applications_service_id_fkey_idx on public.applications (service_id);
create index if not exists applications_order_id_fkey_idx on public.applications (order_id);
create index if not exists applications_assigned_staff_id_fkey_idx on public.applications (assigned_staff_id);
create index if not exists applications_certificate_document_id_fkey_idx on public.applications (certificate_document_id);
create index if not exists branches_business_id_fkey_idx on public.branches (business_id);
create index if not exists branches_address_id_fkey_idx on public.branches (address_id);
create index if not exists business_addresses_business_id_fkey_idx on public.business_addresses (business_id);
create index if not exists business_people_business_id_fkey_idx on public.business_people (business_id);
create index if not exists business_profiles_created_by_fkey_idx on public.business_profiles (created_by);
create index if not exists compliance_results_rule_id_fkey_idx on public.compliance_results (rule_id);
create index if not exists compliance_rule_versions_created_by_fkey_idx on public.compliance_rule_versions (created_by);
create index if not exists compliance_rule_versions_approved_by_fkey_idx on public.compliance_rule_versions (approved_by);
create index if not exists compliance_rules_service_id_fkey_idx on public.compliance_rules (service_id);
create index if not exists compliance_rules_verified_by_fkey_idx on public.compliance_rules (verified_by);
create index if not exists consent_records_user_id_fkey_idx on public.consent_records (user_id);
create index if not exists consent_records_business_id_fkey_idx on public.consent_records (business_id);
create index if not exists customer_actions_application_id_fkey_idx on public.customer_actions (application_id);
create index if not exists documents_person_id_fkey_idx on public.documents (person_id);
create index if not exists documents_uploaded_by_fkey_idx on public.documents (uploaded_by);
create index if not exists government_queries_application_id_fkey_idx on public.government_queries (application_id);
create index if not exists licenses_business_id_fkey_idx on public.licenses (business_id);
create index if not exists licenses_branch_id_fkey_idx on public.licenses (branch_id);
create index if not exists licenses_service_id_fkey_idx on public.licenses (service_id);
create index if not exists licenses_certificate_document_id_fkey_idx on public.licenses (certificate_document_id);
create index if not exists orders_business_id_fkey_idx on public.orders (business_id);
create index if not exists payments_business_id_fkey_idx on public.payments (business_id);
create index if not exists payments_order_id_fkey_idx on public.payments (order_id);
create index if not exists subscriptions_business_id_fkey_idx on public.subscriptions (business_id);
create index if not exists workflow_tasks_application_id_fkey_idx on public.workflow_tasks (application_id);
create index if not exists workflow_tasks_assigned_to_fkey_idx on public.workflow_tasks (assigned_to);

-- Avoid overlapping permissive SELECT policies while retaining staff mutation access.
drop policy if exists catalog_staff_write_services on public.services;
drop policy if exists catalog_staff_write_rules on public.compliance_rules;
drop policy if exists catalog_staff_write_rule_versions on public.compliance_rule_versions;
drop policy if exists catalog_staff_write_workflows on public.workflow_definitions;
drop policy if exists workflow_tasks_staff_write on public.workflow_tasks;
drop policy if exists application_events_staff_write on public.application_events;
drop policy if exists government_queries_staff_write on public.government_queries;

create policy services_staff_insert on public.services for insert to authenticated with check ((select private.is_staff()));
create policy services_staff_update on public.services for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy services_staff_delete on public.services for delete to authenticated using ((select private.is_staff()));
create policy rules_staff_insert on public.compliance_rules for insert to authenticated with check ((select private.is_staff()));
create policy rules_staff_update on public.compliance_rules for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy rules_staff_delete on public.compliance_rules for delete to authenticated using ((select private.is_staff()));
create policy rule_versions_staff_insert on public.compliance_rule_versions for insert to authenticated with check ((select private.is_staff()));
create policy rule_versions_staff_update on public.compliance_rule_versions for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy rule_versions_staff_delete on public.compliance_rule_versions for delete to authenticated using ((select private.is_staff()));
create policy workflows_staff_insert on public.workflow_definitions for insert to authenticated with check ((select private.is_staff()));
create policy workflows_staff_update on public.workflow_definitions for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy workflows_staff_delete on public.workflow_definitions for delete to authenticated using ((select private.is_staff()));
create policy workflow_tasks_staff_insert on public.workflow_tasks for insert to authenticated with check ((select private.is_staff()));
create policy workflow_tasks_staff_update on public.workflow_tasks for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy workflow_tasks_staff_delete on public.workflow_tasks for delete to authenticated using ((select private.is_staff()));
create policy application_events_staff_insert on public.application_events for insert to authenticated with check ((select private.is_staff()));
create policy application_events_staff_update on public.application_events for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy application_events_staff_delete on public.application_events for delete to authenticated using ((select private.is_staff()));
create policy government_queries_staff_insert on public.government_queries for insert to authenticated with check ((select private.is_staff()));
create policy government_queries_staff_update on public.government_queries for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy government_queries_staff_delete on public.government_queries for delete to authenticated using ((select private.is_staff()));
